name: Release Manager Demo - SonarQube

on:
  push:
    branches:
      - feature/sonarqube

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=Swapnil1092_release-manager-demo
            -Dsonar.organization=swapnil1092